ADD: Implement FastAPI application with model loading and prediction endpoint; update Dockerfile and requirements

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,19 +11,19 @@ on:
     workflow_dispatch:
 
 jobs:
-  register-data:
-    runs-on: 
-        - self-hosted
-        - Linux
-        - X64
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+  # register-data:
+  #   runs-on: 
+  #       - self-hosted
+  #       - Linux
+  #       - X64
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4
 
-      - name: Azure -- Login
-        uses: Azure/login@v1
-        with:
-          creds: ${{ secrets.AZURE_CREDENTIALS }}
+  #     - name: Azure -- Login
+  #       uses: Azure/login@v1
+  #       with:
+  #         creds: ${{ secrets.AZURE_CREDENTIALS }}
 
   #     # - name: Install az ml extension
   #     #   run: |
@@ -40,13 +40,13 @@ jobs:
   #     #         --version ${{ github.run_id }} \
   #     #       --set path=/mnt/c/Users/Atvar/Desktop/SEM5/MLOps/MLops-Final-Project/Data/SkinDiseaseSmaller
       
-      - name: Create compute instance if not exists
-        run: |
-          az extension remove -n ml || true
-          az extension add -n ml -y
-          az ml compute create --file ./environments/preprocessing_compute_instance.yaml \
-            --resource-group ${{ secrets.RESOURCE_GROUP }} \
-            --workspace-name ${{ secrets.WORKSPACE_NAME }}
+      # - name: Create compute instance if not exists
+      #   run: |
+      #     az extension remove -n ml || true
+      #     az extension add -n ml -y
+      #     az ml compute create --file ./environments/preprocessing_compute_instance.yaml \
+      #       --resource-group ${{ secrets.RESOURCE_GROUP }} \
+      #       --workspace-name ${{ secrets.WORKSPACE_NAME }}
 
   #     # - name: Start compute instance if stopped
   #     #   run: |
@@ -88,12 +88,54 @@ jobs:
 # --set name=create-labels-cli-${{ github.sha }}-${{ github.run_id }} inputs.path_to_data_root=azureml:skin-disease-data:${{ github.run_id }}
 
 
-  train-model:
-    needs: register-data
-    runs-on: 
-        - self-hosted
-        - Linux
-        - X64
+  # train-model:
+  #   # needs: register-data
+  #   runs-on: 
+  #       - self-hosted
+  #       - Linux
+  #       - X64
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4
+
+  #     - name: Azure -- Login
+  #       uses: Azure/login@v1
+  #       with:
+  #         creds: ${{ secrets.AZURE_CREDENTIALS }}
+
+  #     - name: Create environment
+  #       run: |
+  #         az ml environment create --conda-file ./environments/python_environments/training.yaml \
+  #           --resource-group ${{ secrets.RESOURCE_GROUP }} \
+  #           --workspace-name ${{ secrets.WORKSPACE_NAME }} \
+  #           --name aml-training-cli \
+  #           --image "mcr.microsoft.com/azureml/minimal-ubuntu22.04-py39-cpu-inference:latest"
+      
+  #     - name: Create training component
+  #       run: |
+  #         az ml component create --file ./components/training.yaml \
+  #           --resource-group ${{ secrets.RESOURCE_GROUP }} \
+  #           --workspace-name ${{ secrets.WORKSPACE_NAME }} \
+  #           --version ${{ github.run_id }}
+        
+  #     - name: Create testing component
+  #       run: |
+  #         az ml component create --file ./components/testing.yaml \
+  #           --resource-group ${{ secrets.RESOURCE_GROUP }} \
+  #           --workspace-name ${{ secrets.WORKSPACE_NAME }} \
+  #           --version ${{ github.run_id }}
+      
+  #     - name: Submit training and testing pipeline job
+  #       run: |
+  #         az ml job create --file ./pipelines/train_test.yaml \
+  #           --resource-group ${{ secrets.RESOURCE_GROUP }} \
+  #           --workspace-name ${{ secrets.WORKSPACE_NAME }} \
+  #           --stream \
+  #           --set name=train-test-pipeline-cli-${{ github.sha }}-${{ github.run_id }} inputs.path_to_data_root.path=azureml:skin-disease-data:20194084614 inputs.path_to_data_root.type=uri_folder inputs.labels_folder.path=azureml:azureml_49298ffe-4d17-4250-b24e-683d821da6ba_output_data_label_folder:1 inputs.labels_folder.type=uri_folder
+
+  build-image:
+    # needs: train-model
+    runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -103,33 +145,29 @@ jobs:
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
 
-      - name: Create environment
+      - name: Install az ml extension
         run: |
-          az ml environment create --conda-file ./environments/python_environments/training.yaml \
-            --resource-group ${{ secrets.RESOURCE_GROUP }} \
-            --workspace-name ${{ secrets.WORKSPACE_NAME }} \
-            --name aml-training-cli \
-            --image "mcr.microsoft.com/azureml/minimal-ubuntu22.04-py39-cpu-inference:latest"
-      
-      - name: Create training component
+          az extension add -n ml -y
+
+      - name: Download model
+      # az ml job download --name train-test-pipeline-cli-${{ github.sha }}-${{ github.run_id }} \
         run: |
-          az ml component create --file ./components/training.yaml \
+          az ml job download --name train-test-pipeline-cli-a2964be706a60f6be31f1c5d2d04d0e8a68450c6-20209764366 \
+            --output-name output_model \
+            --download-path ./model_download \
             --resource-group ${{ secrets.RESOURCE_GROUP }} \
-            --workspace-name ${{ secrets.WORKSPACE_NAME }} \
-            --version ${{ github.run_id }}
-        
-      - name: Create testing component
+            --workspace-name ${{ secrets.WORKSPACE_NAME }}
+          
+          MODEL_PATH=$(find ./model_download -name "trained_model.h5" | head -n 1)
+          if [ -z "$MODEL_PATH" ]; then
+            echo "Model file not found!"
+            exit 1
+          fi
+          
+          mv "$MODEL_PATH" ./app/trained_model.h5
+
+      - name: Build Docker image
         run: |
-          az ml component create --file ./components/testing.yaml \
-            --resource-group ${{ secrets.RESOURCE_GROUP }} \
-            --workspace-name ${{ secrets.WORKSPACE_NAME }} \
-            --version ${{ github.run_id }}
-      
-      - name: Submit training and testing pipeline job
-        run: |
-          az ml job create --file ./pipelines/train_test.yaml \
-            --resource-group ${{ secrets.RESOURCE_GROUP }} \
-            --workspace-name ${{ secrets.WORKSPACE_NAME }} \
-            --stream \
-            --set name=train-test-pipeline-cli-${{ github.sha }}-${{ github.run_id }} inputs.path_to_data_root.path=azureml:skin-disease-data:20194084614 inputs.path_to_data_root.type=uri_folder inputs.labels_folder.path=azureml:azureml_49298ffe-4d17-4250-b24e-683d821da6ba_output_data_label_folder:1 inputs.labels_folder.type=uri_folder
+          cd app
+          docker build -t skin-disease-prediction:latest .
           
